# Generated by Django 4.0.2 on 2022-03-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('dirección', models.CharField(max_length=300)),
                ('nit', models.CharField(max_length=300, unique=True)),
                ('tel', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
